# Generated by Django 5.1.3 on 2024-11-12 11:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('userAuth', '0002_customuser_is_company_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Transaction ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Transaction Amount')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Transaction Status')),
                ('transaction_type', models.CharField(choices=[('user_to_user', 'User to User'), ('service_payment', 'Service Payment')], default='user_to_user', max_length=20, verbose_name='Transaction Type')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('recipient_wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_transactions', to='userAuth.wallet')),
                ('sender_wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_transactions', to='userAuth.wallet')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_transactions', to='userAuth.service')),
            ],
        ),
    ]
