# Generated by Django 5.1.3 on 2024-12-03 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_transaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='recipient_wallet',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='sender_wallet',
        ),
        migrations.AddField(
            model_name='transaction',
            name='assurance',
            field=models.BooleanField(default=False, verbose_name='assurance'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('CARTE_CREDIT', 'Carte de Credit'), ('PAYPAL', 'Paypal'), ('ORANGE_MONEY', 'Orange Money'), ('MTN_MOMO', 'MTN MoMo')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='receiver_type',
            field=models.CharField(blank=True, choices=[('famille', 'famille'), ('entreprise', 'entreprise')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_transactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
