# Generated by Django 5.1.3 on 2024-12-09 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_transaction_recipient_wallet_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='recipient',
            new_name='receiver',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='assurance',
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount_assur',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='assur Amount'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(blank=True, choices=[('USD', 'USD'), ('XAF', 'XAF'), ('EUR', 'EUR')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('CARTE_CREDIT', 'Carte de Credit'), ('PAYPAL', 'Paypal'), ('ORANGE_MONEY', 'Orange Money'), ('MTN_MOMO', 'MTN MoMo'), ('PossaPay', 'PossaPay')], default='PossaPay', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('lock', 'lock'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Transaction Status'),
        ),
    ]
