# Generated by Django 5.1.5 on 2025-02-07 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_transaction_receiver_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('service_payment', 'Service Payment'), ('recharge', 'Recharge'), ('envoi', 'Envoi'), ('retrait', 'Retrait')], default='user_to_user', max_length=20, verbose_name='Transaction Type'),
        ),
    ]
