# Generated by Django 5.1.5 on 2025-04-13 15:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_core', '0001_initial'),
        ('userAuth', '0004_alter_service_public_key_alter_service_secret_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apicoretransactions',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='apicoretransactions',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Paid amount'),
        ),
        migrations.AddField(
            model_name='apicoretransactions',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Transaction date'),
        ),
        migrations.AddField(
            model_name='apicoretransactions',
            name='currency',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='apicoretransactions',
            name='payment_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Payment type'),
        ),
        migrations.AddField(
            model_name='apicoretransactions',
            name='productId',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Product unique identifier'),
        ),
        migrations.AddField(
            model_name='apicoretransactions',
            name='productName',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Product Name'),
        ),
        migrations.AddField(
            model_name='apicoretransactions',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userAuth.service'),
        ),
        migrations.AddField(
            model_name='apicoretransactions',
            name='transaction_status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Transaction status'),
        ),
        migrations.AddField(
            model_name='apicoretransactions',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='apicoretransactions',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id'),
        ),
    ]
