# Generated by Django 5.1.5 on 2025-03-13 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='public_key',
            field=models.CharField(default='f33443c8edde8ec930b1bd91fa7c998f14b0607161da7e58c8b7df34f826543a', max_length=64, unique=True, verbose_name='Public Key'),
        ),
        migrations.AlterField(
            model_name='service',
            name='secret_key',
            field=models.CharField(default='4743367ca5581e5dde4f0377eaa18aee6a4b967b764b2127b7a8c9e38aa1ee2f', max_length=64, unique=True, verbose_name='Secret Key'),
        ),
    ]
