# Generated by Django 5.1.3 on 2024-11-12 11:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_company',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('name', models.CharField(max_length=255, verbose_name='Service Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Service Description')),
                ('public_key', models.CharField(default='18ef82656a9b1606d825b6f78560989a98847f71f9fe5ad08c1bb5fe50d4a0be', max_length=64, unique=True, verbose_name='Public Key')),
                ('secret_key', models.CharField(default='401898cad63161bbbd48d9c2439987c3f65ee1d6bfd5cb1a7f4e62ee92bca3d9', max_length=64, unique=True, verbose_name='Secret Key')),
                ('allowed_hosts', models.TextField(blank=True, help_text='Liste de domaines autorisés, séparés par des virgules', null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userAuth.wallet')),
            ],
        ),
    ]
