# Generated by Django 5.1.3 on 2024-11-19 14:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0002_customuser_is_company_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='wallet',
        ),
        migrations.AlterField(
            model_name='service',
            name='public_key',
            field=models.CharField(default='b76dd540cbdb3b909e9a20ba2eb530859536bbe71e0778fad1262bfe20d1fee6', max_length=64, unique=True, verbose_name='Public Key'),
        ),
        migrations.AlterField(
            model_name='service',
            name='secret_key',
            field=models.CharField(default='98a40119f131bc855c66eea755a8135433dee81be593d4088be97d7165ac78d7', max_length=64, unique=True, verbose_name='Secret Key'),
        ),
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='User amount')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('service_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='compte',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userAuth.compte'),
        ),
    ]
