# Generated by Django 5.1.5 on 2025-04-09 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0002_alter_service_public_key_alter_service_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='public_key',
            field=models.CharField(default='159f092da9bc5f8b9eebaf89f1edd7a4356673ab7ec23050e2f1fc38e544671f', max_length=64, unique=True, verbose_name='Public Key'),
        ),
        migrations.AlterField(
            model_name='service',
            name='secret_key',
            field=models.CharField(default='53e6d3222fd51fb8a4cbaa1f8eb8b26beeb9eb1b3eb79a8e6ad91ebfd54f4ef5', max_length=64, unique=True, verbose_name='Secret Key'),
        ),
    ]
