# Generated by Django 5.1.5 on 2025-04-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0003_alter_service_public_key_alter_service_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='public_key',
            field=models.CharField(default='362cbd6ba91c6a68d155c6c8a3a69fc59450ce1e01b61a709921987f4ce9eb29', max_length=64, unique=True, verbose_name='Public Key'),
        ),
        migrations.AlterField(
            model_name='service',
            name='secret_key',
            field=models.CharField(default='63951741e8cf2fe4e98d4111029b577b60e887e7c167bb75b94f0a0bc3339a0e', max_length=64, unique=True, verbose_name='Secret Key'),
        ),
    ]
