# Generated by Django 5.1.3 on 2024-12-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0003_remove_service_wallet_alter_service_public_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compte',
            name='service_id',
        ),
        migrations.AlterField(
            model_name='service',
            name='public_key',
            field=models.CharField(default='faa244d075350a56c5190adc0d9d07bd441f8ee5fd7fcde7da261763e0a39541', max_length=64, unique=True, verbose_name='Public Key'),
        ),
        migrations.AlterField(
            model_name='service',
            name='secret_key',
            field=models.CharField(default='869abad0c6b41f7d01e5849765b06283e31bb8340d4a6dfa632b7936552b4b8b', max_length=64, unique=True, verbose_name='Secret Key'),
        ),
    ]
