# Generated by Django 5.1.3 on 2024-12-09 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0004_remove_compte_service_id_alter_service_public_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='public_key',
            field=models.CharField(default='a7afa7ac26fcc68662ae8aaa3e7901be6b9d52db14a8faf90100eeedc5d915b9', max_length=64, unique=True, verbose_name='Public Key'),
        ),
        migrations.AlterField(
            model_name='service',
            name='secret_key',
            field=models.CharField(default='d35b630015e913138b4ea788280eeb53311ba3728d162219759d446afeebb3ed', max_length=64, unique=True, verbose_name='Secret Key'),
        ),
    ]
