# Generated by Django 5.1.3 on 2024-12-11 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0005_alter_service_public_key_alter_service_secret_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='devise',
            field=models.CharField(blank=True, choices=[('USD', 'USD'), ('XAF', 'XAF'), ('EUR', 'EUR')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='public_key',
            field=models.CharField(default='3b5bc17fa5ce60a5879f263cbd5cf2a2304e298d48a4dc2a2c2329561aee223d', max_length=64, unique=True, verbose_name='Public Key'),
        ),
        migrations.AlterField(
            model_name='service',
            name='secret_key',
            field=models.CharField(default='37bfc7d976cd68687d4fa4fa33c2afe67da49a89ef1ea8d23c47de7f2ad3e8e0', max_length=64, unique=True, verbose_name='Secret Key'),
        ),
    ]
