# Generated by Django 5.1.3 on 2024-12-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0006_wallet_devise_alter_service_public_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='public_key',
            field=models.CharField(default='465d6019421cdf66f34923ecedc5eda884136d007d96be2502391004bf32055b', max_length=64, unique=True, verbose_name='Public Key'),
        ),
        migrations.AlterField(
            model_name='service',
            name='secret_key',
            field=models.CharField(default='a44c54d72e325551788f6e1b40037dffa79ec82b4bbdbcab32971d19bf2a1050', max_length=64, unique=True, verbose_name='Secret Key'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='devise',
            field=models.CharField(blank=True, choices=[('USD', 'USD'), ('XAF', 'XAF'), ('EUR', 'EUR')], default='XAF', max_length=5, null=True),
        ),
    ]
