# Generated by Django 5.1.3 on 2024-12-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0007_alter_service_public_key_alter_service_secret_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='public_key',
            field=models.CharField(default='4939d6da4ee0e7b9d9429ae17ecd5d98f5cb2b12037747fafe8b6f0c06fc4db2', max_length=64, unique=True, verbose_name='Public Key'),
        ),
        migrations.AlterField(
            model_name='service',
            name='secret_key',
            field=models.CharField(default='6a3689e7f570fb6c33755abe2300393ccf237674f657de66226aa955f8d54168', max_length=64, unique=True, verbose_name='Secret Key'),
        ),
    ]
