# Generated by Django 5.1.3 on 2024-12-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0008_customuser_country_alter_service_public_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='public_key',
            field=models.CharField(default='5ccc62681e0ff2d66c559debf79aca0def2b5cf9befea3c4efe13ca5cb7f85e1', max_length=64, unique=True, verbose_name='Public Key'),
        ),
        migrations.AlterField(
            model_name='service',
            name='secret_key',
            field=models.CharField(default='a20978152e5846f8d1792452b52ae10b5c3489e727f2274074f5e6ac04bb72e2', max_length=64, unique=True, verbose_name='Secret Key'),
        ),
    ]
