# Generated by Django 5.1.3 on 2024-12-29 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0009_alter_service_public_key_alter_service_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='public_key',
            field=models.CharField(default='6aa9a3d93f7f2c1114a839d7702812efdcbe06a668206b7aef91be71021eeee5', max_length=64, unique=True, verbose_name='Public Key'),
        ),
        migrations.AlterField(
            model_name='service',
            name='secret_key',
            field=models.CharField(default='ef51da3cd24ebbd67b467477ca949bab4b7dbeb3ffdc0c025a857153e5d1dc46', max_length=64, unique=True, verbose_name='Secret Key'),
        ),
    ]
