# Generated by Django 5.1.3 on 2025-01-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0010_alter_service_public_key_alter_service_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='public_key',
            field=models.CharField(default='96a00305bf1a66542c12f805e4da8d4cce590ebe6d9c7822e9c749721a4bd91a', max_length=64, unique=True, verbose_name='Public Key'),
        ),
        migrations.AlterField(
            model_name='service',
            name='secret_key',
            field=models.CharField(default='5bb9c8eb753cd4f1230a805075d3307f348f805a1cb7b6b80724a11faf32f9a8', max_length=64, unique=True, verbose_name='Secret Key'),
        ),
    ]
