# Generated by Django 5.1.5 on 2025-02-07 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0011_alter_service_public_key_alter_service_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='public_key',
            field=models.CharField(default='1626c9099edbf449424f714cb30c02f8fa97b9991a8ea90b04aceb655048fe03', max_length=64, unique=True, verbose_name='Public Key'),
        ),
        migrations.AlterField(
            model_name='service',
            name='secret_key',
            field=models.CharField(default='eacfff78f9ddac081e4c53f34828484b3a783c65ba58cbc690164871427f3773', max_length=64, unique=True, verbose_name='Secret Key'),
        ),
    ]
