# Generated by Django 5.1.5 on 2025-04-11 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0012_alter_service_public_key_alter_service_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='public_key',
            field=models.CharField(default='974c91ef05eda29d2b580e8d83e2c45a43c8421d00082a0b66544115ac2d5502', max_length=64, unique=True, verbose_name='Public Key'),
        ),
        migrations.AlterField(
            model_name='service',
            name='secret_key',
            field=models.CharField(default='a75b5b620bbbb33391d4aa3301f15ab17c63ed09074bef222423ff9e5a75fc09', max_length=64, unique=True, verbose_name='Secret Key'),
        ),
    ]
