# Generated by Django 5.1.5 on 2025-04-11 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0013_alter_service_public_key_alter_service_secret_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='allowed_hosts',
        ),
        migrations.AlterField(
            model_name='service',
            name='public_key',
            field=models.CharField(default='fa6b332d4951faa150eb521aad35519ddda10705cef0330125231ba670d324b0', max_length=64, unique=True, verbose_name='Public Key'),
        ),
        migrations.AlterField(
            model_name='service',
            name='secret_key',
            field=models.CharField(default='dfef93fbccdf513d1122b462987fc2206137e5e41270d93998fd207769819dba', max_length=64, unique=True, verbose_name='Secret Key'),
        ),
        migrations.CreateModel(
            name='AllowedHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_hosts', to='userAuth.service')),
            ],
        ),
    ]
