# Generated by Django 5.1.5 on 2025-05-05 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0014_remove_service_allowed_hosts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compte',
            name='devise',
            field=models.CharField(blank=True, choices=[('USD', 'USD'), ('XAF', 'XAF'), ('EUR', 'EUR')], default='XAF', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='public_key',
            field=models.CharField(default='706190777b3c52d25046f77f170012d66106459277e99b23f157a1cb6af71cc8', max_length=64, unique=True, verbose_name='Public Key'),
        ),
        migrations.AlterField(
            model_name='service',
            name='secret_key',
            field=models.CharField(default='a8991d0508e9ef0429747f79a6087c96ae22880f872dc853ae8bbfa688c8343b', max_length=64, unique=True, verbose_name='Secret Key'),
        ),
    ]
